version: "3"
services:
    node:
        image: node:6.10-alpine
        links:
            - redis
        ports:
            - "8080:80"
        volumes:
            - "./node/code:/code"
        working_dir: "/code"
        command: ["node", "index.js"]
    redis:
        image: redis:3.2
        ports:
            - "6379:6379"
        volumes:
            - "./redis/data:/data"
